package com.instant.common;

/**
 * @author sroshchupkin
 */
public interface Constants {
    String VENUE_ADDRESS = "VENUE_ADDRESS";
    String VENUE_DESCRIPTION = "VENUE_DESCRIPTION";
    String VENUE_ID = "VENUE_ID";
    String VENUE_IMAGE_PATH = "VENUE_IMAGE_PATH";
    String VENUE_NAME = "VENUE_NAME";
    String VENUE_COUNTRY = "VENUE_COUNTRY";
    String VENUE_CITY = "VENUE_CITY";
    String VENUE_TYPE = "VENUE_TYPE";
    String VENUE_CATEGORY = "VENUE_CATEGORY";
    String VENUE_COMPANY = "VENUE_COMPANY";
    String VENUE_MAIN_IMAGE_PATH = "VENUE_MAIN_IMAGE_PATH";
    String VENUE_SPECIALITIES = "VENUE_SPECIALITY";
    String VENUE_EMAIL = "VENUE_EMAIL";
    String VENUE_TELEPHONE_PRIMARY = "VENUE_TELEPHONE_PRIMARY";
    String VENUE_TELEPHONE_SECONDARY = "VENUE_TELEPHONE_SECONDARY";
    String VENUE_MOBILE_PRIMARY = "VENUE_MOBILE_PRIMARY";
    String VENUE_MOBILE_SECONDARY = "VENUE_MOBILE_SECONDARY";
    String VENUE_FACEBOOK_PAGE = "VENUE_FACEBOOK_PAGE";
    String VENUE_WEBSITE = "VENUE_WEBSITE";
}
